services:
  nacos:
    image: nacos/nacos-server:v2.5.1
    ports:
      - "8848:8848"
      - "9848:9848"    # Cluster communication port
      - "9849:9849"    # Cluster management port
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
    healthcheck:
      test: 'curl -Ss http://localhost:8848/nacos'
      interval: 5s
      timeout: 5s
      retries: 40