spring:
  cloud:
    consul:
      host: localhost
      port: 59081
      discovery:
        register: true
        service-name: message-service
  application:
    name: message-rpc-server
  lifecycle:
    timeout-per-shutdown-phase: "2m"
  main:
    allow-bean-definition-overriding: true

server:
  port: 8581
  http2:
    enabled: true

grpc:
  server:
    address: 0.0.0.0
    port: 59081

management:
  health:
    diskspace:
      enabled: false
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health'

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
logging:
  pattern:
    console: "{ \"datetime\": \"%d{yyyy-MM-dd HH:mm:ss.SSS}\", \"level\": \"%level\", \"traceId\": \"%mdc{traceId}\", \"spanId\": \"%mdc{spanId}\", \"thread\": \"%thread\", \"class\": \"%c{2.}\", \"message\": \"%m\"}%n"