version: '3.8'

services:
  message-rpc-server:
    image: nanachi1027/message-rpc-server:latest
    container_name: message-rpc-server
    ports:
      - "8581:8581"
      - "59081:59081"
    environment:
      SPRING_APPLICATION_NAME: grpc-server
      SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: "2m"
      SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
      SERVER_PORT: 8581
      SERVER_HTTP2_ENABLED: "true"
      GRPC_SERVER_ADDRESS: "0.0.0.0"  # Bind to all interfaces for accessibility
      GRPC_SERVER_PORT: 59081
      MANAGEMENT_HEALTH_DISKSPACE_ENABLED: "false"
      MANAGEMENT_TRACING_ENABLED: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
      MANAGEMENT_ENDPOINTS_ENABLED_BY_DEFAULT: "false"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health"
      MANAGEMENT_ENDPOINT_INFO_ENABLED: "true"
      MANAGEMENT_ENDPOINT_HEALTH_ENABLED: "true"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      LOGGING_PATTERN_CONSOLE: "{ \"datetime\": \"%d{yyyy-MM-dd HH:mm:ss.SSS}\", \"level\": \"%level\", \"traceId\": \"%mdc{traceId}\", \"spanId\": \"%mdc{spanId}\", \"thread\": \"%thread\", \"class\": \"%c{2.}\", \"message\": \"%m\"}%n"
    networks:
      - message-network

  message-web:
    image: docker.io/nanachi1027/message-web:latest
    container_name: message-web
    ports:
      - "8580:8580"
    environment:
      SERVER_PORT: 8580
      MESSAGE_SERVICE_HOST: message-rpc-server  # Use container name for networking
      MESSAGE_SERVICE_PORT: 59081
    depends_on:
      - message-rpc-server
    networks:
      - message-network
  gateway-service:
    image: docker.io/nanachi1027/gateway-service:latest  # Use docker.io/nanachi1027 for the image
    container_name: gateway-service
    ports:
      - "9994:9994"  # Expose the gateway service to external world
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: "lb://RPC-SERVER"
      SPRING_CLOUD_GATEWAY_ROUTES_0_PATH: "/rpc/server/**"
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: "lb://RPC-CLIENT"
      SPRING_CLOUD_GATEWAY_ROUTES_1_PATH: "/rpc/client/**"
    depends_on:
      - message-rpc-server  # Ensure the rpc server is available before starting the gateway
      - activemq
      - zipkin
    networks:
      - message-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - message-network

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"  # ActiveMQ broker port
      - "8161:8161"    # ActiveMQ Web Console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - message-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - message-network

networks:
  message-network:
    driver: bridge