spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_pay?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # options：validate / update / create / create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

dubbo:
  application:
    name: service-message
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: tri
    port: 50052


