server:
  port: 9994

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: rpc-server
          uri: lb://RPC-SERVER
          predicates:
            - Path=/rpc/server/**
          filters:
            - StripPrefix=1
        - id: rpc-client
          uri: lb://RPC-CLIENT
          predicates:
            - Path=/rpc/client/**
          filters:
            - StripPrefix=1