version: '3'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - ZIPKIN_UI=1
    networks:
      - zipkin-net
    restart: always

networks:
  zipkin-net:
    driver: bridge