name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  common-core:
    name: Build Common Core
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Working Directory
        run: |
          cd distributed-sys-payments

      - name: Set Up JDK 17 & Maven
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build & Install Common Core
        run: |
          cd distributed-sys-payments/common-core
          mvn clean install
          echo "✅ Common Core JAR installed in Maven repository."

      - name: Upload Common Core JAR
        uses: actions/upload-artifact@v4
        with:
          name: common-core-jar
          path: ~/.m2/repository/com/distributed/sys/payments/common-core/

  service-message-api:
    name: Build Service Message API
    runs-on: ubuntu-latest
    needs: common-core

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Working Directory
        run: |
          cd distributed-sys-payments

      - name: Set Up JDK 17 & Maven
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Download Common Core JAR
        uses: actions/download-artifact@v4
        with:
          name: common-core-jar
          path: ~/.m2/repository/com/distributed/sys/payments/common-core/

      - name: Build & Install Service Message API
        run: |
          cd distributed-sys-payments/service-message-api
          mvn clean install
          echo "✅ Service Message API JAR installed in Maven repository."

      - name: Upload Service Message API JAR
        uses: actions/upload-artifact@v4
        with:
          name: service-message-api-jar
          path: ~/.m2/repository/com/distributed/sys/payments/service-message-api/

  service-provider:
    name: Build Service Provider
    runs-on: ubuntu-latest
    needs: service-message-api

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: mini/pay
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Working Directory
        run: |
          cd distributed-sys-payments

      - name: Set Up JDK 17 & Maven
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Download Common Core JAR
        uses: actions/download-artifact@v4
        with:
          name: common-core-jar
          path: ~/.m2/repository/com/distributed/sys/payments/common-core/

      - name: Download Service Message API JAR
        uses: actions/download-artifact@v4
        with:
          name: service-message-api-jar
          path: ~/.m2/repository/com/distributed/sys/payments/service-message-api/

      - name: Verify MySQL Connection
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -uadmin -padmin -e "SHOW DATABASES;"

      - name: Build & Install Service Provider
        run: |
          cd distributed-sys-payments/service-provider
          mvn clean install
          echo "✅ Service Provider JAR installed in Maven repository."

      - name: Upload Service Provider JAR
        uses: actions/upload-artifact@v4
        with:
          name: service-provider-jar
          path: ~/.m2/repository/com/distributed/sys/payments/service-provider/
